name: strep_detect
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pytorch=2.3.*
  - torchvision=0.18.*
  - tensorflow-gpu
  - matplotlib
  - numpy
  - pandas
  - pillow
  - unzip
